/**
 * Dữ liệu điểm học viên trích xuất từ file du_lieu_mshv_y_khoa_200_dong.xlsx
 * Tổng số học viên: 200
 */
window.DEFAULT_STUDENTS_DATA = [
  {
    "stt": 1,
    "mshv": "YK2026-0001",
    "hoTen": "Nguyễn Minh Đức Khoa",
    "ngaySinh": "12/06/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.7,
    "diemThiFormatted": "7.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 2,
    "mshv": "YK2026-0002",
    "hoTen": "Trần Hoàng Hải Quân",
    "ngaySinh": "23/11/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.3,
    "diemThiFormatted": "5.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 3,
    "mshv": "YK2026-0003",
    "hoTen": "Lê Quốc Linh Bình",
    "ngaySinh": "07/04/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9,
    "diemThiFormatted": "9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 4,
    "mshv": "YK2026-0004",
    "hoTen": "Phạm Gia Phúc Lâm",
    "ngaySinh": "18/09/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.6,
    "diemThiFormatted": "6.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 5,
    "mshv": "YK2026-0005",
    "hoTen": "Huỳnh Anh Trang Sơn",
    "ngaySinh": "02/02/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.2,
    "diemThiFormatted": "4.2",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 6,
    "mshv": "YK2026-0006",
    "hoTen": "Võ Thanh Yến Châu",
    "ngaySinh": "13/07/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.9,
    "diemThiFormatted": "7.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 7,
    "mshv": "YK2026-0007",
    "hoTen": "Đặng Khánh Bảo Long",
    "ngaySinh": "24/12/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.5,
    "diemThiFormatted": "5.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 8,
    "mshv": "YK2026-0008",
    "hoTen": "Bùi Đức Gia Tâm",
    "ngaySinh": "08/05/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.2,
    "diemThiFormatted": "9.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 9,
    "mshv": "YK2026-0009",
    "hoTen": "Đỗ Thùy Khánh Dũng",
    "ngaySinh": "19/10/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.8,
    "diemThiFormatted": "6.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 10,
    "mshv": "YK2026-0010",
    "hoTen": "Phan Nhật Mai My",
    "ngaySinh": "03/03/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.4,
    "diemThiFormatted": "4.4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 11,
    "mshv": "YK2026-0011",
    "hoTen": "Ngô Hải Quỳnh Thư",
    "ngaySinh": "14/08/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.1,
    "diemThiFormatted": "8.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 12,
    "mshv": "YK2026-0012",
    "hoTen": "Dương Bảo Uyên Giang",
    "ngaySinh": "25/01/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.7,
    "diemThiFormatted": "5.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 13,
    "mshv": "YK2026-0013",
    "hoTen": "Hoàng Mai Minh Nam",
    "ngaySinh": "09/06/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.4,
    "diemThiFormatted": "9.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 14,
    "mshv": "YK2026-0014",
    "hoTen": "Vũ Ngọc Cẩm Trang",
    "ngaySinh": "20/11/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7,
    "diemThiFormatted": "7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 15,
    "mshv": "YK2026-0015",
    "hoTen": "Lý Quang Hà Hạnh",
    "ngaySinh": "04/04/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.6,
    "diemThiFormatted": "4.6",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 16,
    "mshv": "YK2026-0016",
    "hoTen": "Tạ Phương Lan Nhi",
    "ngaySinh": "15/09/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.3,
    "diemThiFormatted": "8.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 17,
    "mshv": "YK2026-0017",
    "hoTen": "Nguyễn Minh Nam Vân",
    "ngaySinh": "26/02/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.9,
    "diemThiFormatted": "5.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 18,
    "mshv": "YK2026-0018",
    "hoTen": "Trần Hoàng Thảo Hiếu",
    "ngaySinh": "10/07/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.6,
    "diemThiFormatted": "9.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 19,
    "mshv": "YK2026-0019",
    "hoTen": "Lê Quốc Việt Phát",
    "ngaySinh": "21/12/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.2,
    "diemThiFormatted": "7.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 20,
    "mshv": "YK2026-0020",
    "hoTen": "Phạm Gia Anh An",
    "ngaySinh": "05/05/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.8,
    "diemThiFormatted": "4.8",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 21,
    "mshv": "YK2026-0021",
    "hoTen": "Huỳnh Anh Đức Khoa",
    "ngaySinh": "16/10/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.5,
    "diemThiFormatted": "8.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 22,
    "mshv": "YK2026-0022",
    "hoTen": "Võ Thanh Hải Quân",
    "ngaySinh": "27/03/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.1,
    "diemThiFormatted": "6.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 23,
    "mshv": "YK2026-0023",
    "hoTen": "Đặng Khánh Linh Bình",
    "ngaySinh": "11/08/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.8,
    "diemThiFormatted": "9.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 24,
    "mshv": "YK2026-0024",
    "hoTen": "Bùi Đức Phúc Lâm",
    "ngaySinh": "22/01/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.4,
    "diemThiFormatted": "7.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 25,
    "mshv": "YK2026-0025",
    "hoTen": "Đỗ Thùy Trang Sơn",
    "ngaySinh": "06/06/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5,
    "diemThiFormatted": "5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 26,
    "mshv": "YK2026-0026",
    "hoTen": "Phan Nhật Yến Châu",
    "ngaySinh": "17/11/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.7,
    "diemThiFormatted": "8.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 27,
    "mshv": "YK2026-0027",
    "hoTen": "Ngô Hải Bảo Long",
    "ngaySinh": "01/04/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.3,
    "diemThiFormatted": "6.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 28,
    "mshv": "YK2026-0028",
    "hoTen": "Dương Bảo Gia Tâm",
    "ngaySinh": "12/09/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 10,
    "diemThiFormatted": "10",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 29,
    "mshv": "YK2026-0029",
    "hoTen": "Hoàng Mai Khánh Dũng",
    "ngaySinh": "23/02/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.6,
    "diemThiFormatted": "7.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 30,
    "mshv": "YK2026-0030",
    "hoTen": "Vũ Ngọc Mai My",
    "ngaySinh": "07/07/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.2,
    "diemThiFormatted": "5.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 31,
    "mshv": "YK2026-0031",
    "hoTen": "Lý Quang Quỳnh Thư",
    "ngaySinh": "18/12/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.9,
    "diemThiFormatted": "8.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 32,
    "mshv": "YK2026-0032",
    "hoTen": "Tạ Phương Uyên Giang",
    "ngaySinh": "02/05/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.5,
    "diemThiFormatted": "6.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 33,
    "mshv": "YK2026-0033",
    "hoTen": "Nguyễn Minh Minh Nam",
    "ngaySinh": "13/10/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.1,
    "diemThiFormatted": "4.1",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 34,
    "mshv": "YK2026-0034",
    "hoTen": "Trần Hoàng Cẩm Trang",
    "ngaySinh": "24/03/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.8,
    "diemThiFormatted": "7.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 35,
    "mshv": "YK2026-0035",
    "hoTen": "Lê Quốc Hà Hạnh",
    "ngaySinh": "08/08/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.4,
    "diemThiFormatted": "5.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 36,
    "mshv": "YK2026-0036",
    "hoTen": "Phạm Gia Lan Nhi",
    "ngaySinh": "19/01/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.1,
    "diemThiFormatted": "9.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 37,
    "mshv": "YK2026-0037",
    "hoTen": "Huỳnh Anh Nam Vân",
    "ngaySinh": "03/06/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.7,
    "diemThiFormatted": "6.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 38,
    "mshv": "YK2026-0038",
    "hoTen": "Võ Thanh Thảo Hiếu",
    "ngaySinh": "14/11/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.3,
    "diemThiFormatted": "4.3",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 39,
    "mshv": "YK2026-0039",
    "hoTen": "Đặng Khánh Việt Phát",
    "ngaySinh": "25/04/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8,
    "diemThiFormatted": "8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 40,
    "mshv": "YK2026-0040",
    "hoTen": "Bùi Đức Anh An",
    "ngaySinh": "09/09/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.6,
    "diemThiFormatted": "5.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 41,
    "mshv": "YK2026-0041",
    "hoTen": "Đỗ Thùy Đức Khoa",
    "ngaySinh": "20/02/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.3,
    "diemThiFormatted": "9.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 42,
    "mshv": "YK2026-0042",
    "hoTen": "Phan Nhật Hải Quân",
    "ngaySinh": "04/07/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.9,
    "diemThiFormatted": "6.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 43,
    "mshv": "YK2026-0043",
    "hoTen": "Ngô Hải Linh Bình",
    "ngaySinh": "15/12/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.5,
    "diemThiFormatted": "4.5",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 44,
    "mshv": "YK2026-0044",
    "hoTen": "Dương Bảo Phúc Lâm",
    "ngaySinh": "26/05/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.2,
    "diemThiFormatted": "8.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 45,
    "mshv": "YK2026-0045",
    "hoTen": "Hoàng Mai Trang Sơn",
    "ngaySinh": "10/10/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.8,
    "diemThiFormatted": "5.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 46,
    "mshv": "YK2026-0046",
    "hoTen": "Vũ Ngọc Yến Châu",
    "ngaySinh": "21/03/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.5,
    "diemThiFormatted": "9.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 47,
    "mshv": "YK2026-0047",
    "hoTen": "Lý Quang Bảo Long",
    "ngaySinh": "05/08/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.1,
    "diemThiFormatted": "7.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 48,
    "mshv": "YK2026-0048",
    "hoTen": "Tạ Phương Gia Tâm",
    "ngaySinh": "16/01/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.7,
    "diemThiFormatted": "4.7",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 49,
    "mshv": "YK2026-0049",
    "hoTen": "Nguyễn Minh Khánh Dũng",
    "ngaySinh": "27/06/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.4,
    "diemThiFormatted": "8.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 50,
    "mshv": "YK2026-0050",
    "hoTen": "Trần Hoàng Mai My",
    "ngaySinh": "11/11/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6,
    "diemThiFormatted": "6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 51,
    "mshv": "YK2026-0051",
    "hoTen": "Lê Quốc Quỳnh Thư",
    "ngaySinh": "22/04/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.7,
    "diemThiFormatted": "9.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 52,
    "mshv": "YK2026-0052",
    "hoTen": "Phạm Gia Uyên Giang",
    "ngaySinh": "06/09/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.3,
    "diemThiFormatted": "7.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 53,
    "mshv": "YK2026-0053",
    "hoTen": "Huỳnh Anh Minh Nam",
    "ngaySinh": "17/02/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.9,
    "diemThiFormatted": "4.9",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 54,
    "mshv": "YK2026-0054",
    "hoTen": "Võ Thanh Cẩm Trang",
    "ngaySinh": "01/07/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.6,
    "diemThiFormatted": "8.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 55,
    "mshv": "YK2026-0055",
    "hoTen": "Đặng Khánh Hà Hạnh",
    "ngaySinh": "12/12/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.2,
    "diemThiFormatted": "6.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 56,
    "mshv": "YK2026-0056",
    "hoTen": "Bùi Đức Lan Nhi",
    "ngaySinh": "23/05/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.9,
    "diemThiFormatted": "9.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 57,
    "mshv": "YK2026-0057",
    "hoTen": "Đỗ Thùy Nam Vân",
    "ngaySinh": "07/10/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.5,
    "diemThiFormatted": "7.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 58,
    "mshv": "YK2026-0058",
    "hoTen": "Phan Nhật Thảo Hiếu",
    "ngaySinh": "18/03/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.1,
    "diemThiFormatted": "5.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 59,
    "mshv": "YK2026-0059",
    "hoTen": "Ngô Hải Việt Phát",
    "ngaySinh": "02/08/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.8,
    "diemThiFormatted": "8.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 60,
    "mshv": "YK2026-0060",
    "hoTen": "Dương Bảo Anh An",
    "ngaySinh": "13/01/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.4,
    "diemThiFormatted": "6.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 61,
    "mshv": "YK2026-0061",
    "hoTen": "Hoàng Mai Đức Khoa",
    "ngaySinh": "24/06/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4,
    "diemThiFormatted": "4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 62,
    "mshv": "YK2026-0062",
    "hoTen": "Vũ Ngọc Hải Quân",
    "ngaySinh": "08/11/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.7,
    "diemThiFormatted": "7.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 63,
    "mshv": "YK2026-0063",
    "hoTen": "Lý Quang Linh Bình",
    "ngaySinh": "19/04/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.3,
    "diemThiFormatted": "5.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 64,
    "mshv": "YK2026-0064",
    "hoTen": "Tạ Phương Phúc Lâm",
    "ngaySinh": "03/09/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9,
    "diemThiFormatted": "9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 65,
    "mshv": "YK2026-0065",
    "hoTen": "Nguyễn Minh Trang Sơn",
    "ngaySinh": "14/02/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.6,
    "diemThiFormatted": "6.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 66,
    "mshv": "YK2026-0066",
    "hoTen": "Trần Hoàng Yến Châu",
    "ngaySinh": "25/07/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.2,
    "diemThiFormatted": "4.2",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 67,
    "mshv": "YK2026-0067",
    "hoTen": "Lê Quốc Bảo Long",
    "ngaySinh": "09/12/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.9,
    "diemThiFormatted": "7.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 68,
    "mshv": "YK2026-0068",
    "hoTen": "Phạm Gia Gia Tâm",
    "ngaySinh": "20/05/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.5,
    "diemThiFormatted": "5.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 69,
    "mshv": "YK2026-0069",
    "hoTen": "Huỳnh Anh Khánh Dũng",
    "ngaySinh": "04/10/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.2,
    "diemThiFormatted": "9.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 70,
    "mshv": "YK2026-0070",
    "hoTen": "Võ Thanh Mai My",
    "ngaySinh": "15/03/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.8,
    "diemThiFormatted": "6.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 71,
    "mshv": "YK2026-0071",
    "hoTen": "Đặng Khánh Quỳnh Thư",
    "ngaySinh": "26/08/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.4,
    "diemThiFormatted": "4.4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 72,
    "mshv": "YK2026-0072",
    "hoTen": "Bùi Đức Uyên Giang",
    "ngaySinh": "10/01/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.1,
    "diemThiFormatted": "8.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 73,
    "mshv": "YK2026-0073",
    "hoTen": "Đỗ Thùy Minh Nam",
    "ngaySinh": "21/06/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.7,
    "diemThiFormatted": "5.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 74,
    "mshv": "YK2026-0074",
    "hoTen": "Phan Nhật Cẩm Trang",
    "ngaySinh": "05/11/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.4,
    "diemThiFormatted": "9.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 75,
    "mshv": "YK2026-0075",
    "hoTen": "Ngô Hải Hà Hạnh",
    "ngaySinh": "16/04/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7,
    "diemThiFormatted": "7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 76,
    "mshv": "YK2026-0076",
    "hoTen": "Dương Bảo Lan Nhi",
    "ngaySinh": "27/09/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.6,
    "diemThiFormatted": "4.6",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 77,
    "mshv": "YK2026-0077",
    "hoTen": "Hoàng Mai Nam Vân",
    "ngaySinh": "11/02/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.3,
    "diemThiFormatted": "8.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 78,
    "mshv": "YK2026-0078",
    "hoTen": "Vũ Ngọc Thảo Hiếu",
    "ngaySinh": "22/07/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.9,
    "diemThiFormatted": "5.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 79,
    "mshv": "YK2026-0079",
    "hoTen": "Lý Quang Việt Phát",
    "ngaySinh": "06/12/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.6,
    "diemThiFormatted": "9.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 80,
    "mshv": "YK2026-0080",
    "hoTen": "Tạ Phương Anh An",
    "ngaySinh": "17/05/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.2,
    "diemThiFormatted": "7.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 81,
    "mshv": "YK2026-0081",
    "hoTen": "Nguyễn Minh Đức Khoa",
    "ngaySinh": "01/10/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.8,
    "diemThiFormatted": "4.8",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 82,
    "mshv": "YK2026-0082",
    "hoTen": "Trần Hoàng Hải Quân",
    "ngaySinh": "12/03/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.5,
    "diemThiFormatted": "8.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 83,
    "mshv": "YK2026-0083",
    "hoTen": "Lê Quốc Linh Bình",
    "ngaySinh": "23/08/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.1,
    "diemThiFormatted": "6.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 84,
    "mshv": "YK2026-0084",
    "hoTen": "Phạm Gia Phúc Lâm",
    "ngaySinh": "07/01/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.8,
    "diemThiFormatted": "9.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 85,
    "mshv": "YK2026-0085",
    "hoTen": "Huỳnh Anh Trang Sơn",
    "ngaySinh": "18/06/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.4,
    "diemThiFormatted": "7.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 86,
    "mshv": "YK2026-0086",
    "hoTen": "Võ Thanh Yến Châu",
    "ngaySinh": "02/11/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5,
    "diemThiFormatted": "5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 87,
    "mshv": "YK2026-0087",
    "hoTen": "Đặng Khánh Bảo Long",
    "ngaySinh": "13/04/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.7,
    "diemThiFormatted": "8.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 88,
    "mshv": "YK2026-0088",
    "hoTen": "Bùi Đức Gia Tâm",
    "ngaySinh": "24/09/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.3,
    "diemThiFormatted": "6.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 89,
    "mshv": "YK2026-0089",
    "hoTen": "Đỗ Thùy Khánh Dũng",
    "ngaySinh": "08/02/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 10,
    "diemThiFormatted": "10",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 90,
    "mshv": "YK2026-0090",
    "hoTen": "Phan Nhật Mai My",
    "ngaySinh": "19/07/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.6,
    "diemThiFormatted": "7.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 91,
    "mshv": "YK2026-0091",
    "hoTen": "Ngô Hải Quỳnh Thư",
    "ngaySinh": "03/12/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.2,
    "diemThiFormatted": "5.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 92,
    "mshv": "YK2026-0092",
    "hoTen": "Dương Bảo Uyên Giang",
    "ngaySinh": "14/05/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.9,
    "diemThiFormatted": "8.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 93,
    "mshv": "YK2026-0093",
    "hoTen": "Hoàng Mai Minh Nam",
    "ngaySinh": "25/10/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.5,
    "diemThiFormatted": "6.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 94,
    "mshv": "YK2026-0094",
    "hoTen": "Vũ Ngọc Cẩm Trang",
    "ngaySinh": "09/03/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.1,
    "diemThiFormatted": "4.1",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 95,
    "mshv": "YK2026-0095",
    "hoTen": "Lý Quang Hà Hạnh",
    "ngaySinh": "20/08/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.8,
    "diemThiFormatted": "7.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 96,
    "mshv": "YK2026-0096",
    "hoTen": "Tạ Phương Lan Nhi",
    "ngaySinh": "04/01/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.4,
    "diemThiFormatted": "5.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 97,
    "mshv": "YK2026-0097",
    "hoTen": "Nguyễn Minh Nam Vân",
    "ngaySinh": "15/06/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.1,
    "diemThiFormatted": "9.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 98,
    "mshv": "YK2026-0098",
    "hoTen": "Trần Hoàng Thảo Hiếu",
    "ngaySinh": "26/11/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.7,
    "diemThiFormatted": "6.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 99,
    "mshv": "YK2026-0099",
    "hoTen": "Lê Quốc Việt Phát",
    "ngaySinh": "10/04/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.3,
    "diemThiFormatted": "4.3",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 100,
    "mshv": "YK2026-0100",
    "hoTen": "Phạm Gia Anh An",
    "ngaySinh": "21/09/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8,
    "diemThiFormatted": "8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 101,
    "mshv": "YK2026-0101",
    "hoTen": "Huỳnh Anh Đức Khoa",
    "ngaySinh": "05/02/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.6,
    "diemThiFormatted": "5.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 102,
    "mshv": "YK2026-0102",
    "hoTen": "Võ Thanh Hải Quân",
    "ngaySinh": "16/07/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.3,
    "diemThiFormatted": "9.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 103,
    "mshv": "YK2026-0103",
    "hoTen": "Đặng Khánh Linh Bình",
    "ngaySinh": "27/12/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.9,
    "diemThiFormatted": "6.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 104,
    "mshv": "YK2026-0104",
    "hoTen": "Bùi Đức Phúc Lâm",
    "ngaySinh": "11/05/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.5,
    "diemThiFormatted": "4.5",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 105,
    "mshv": "YK2026-0105",
    "hoTen": "Đỗ Thùy Trang Sơn",
    "ngaySinh": "22/10/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.2,
    "diemThiFormatted": "8.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 106,
    "mshv": "YK2026-0106",
    "hoTen": "Phan Nhật Yến Châu",
    "ngaySinh": "06/03/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.8,
    "diemThiFormatted": "5.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 107,
    "mshv": "YK2026-0107",
    "hoTen": "Ngô Hải Bảo Long",
    "ngaySinh": "17/08/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.5,
    "diemThiFormatted": "9.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 108,
    "mshv": "YK2026-0108",
    "hoTen": "Dương Bảo Gia Tâm",
    "ngaySinh": "01/01/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.1,
    "diemThiFormatted": "7.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 109,
    "mshv": "YK2026-0109",
    "hoTen": "Hoàng Mai Khánh Dũng",
    "ngaySinh": "12/06/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.7,
    "diemThiFormatted": "4.7",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 110,
    "mshv": "YK2026-0110",
    "hoTen": "Vũ Ngọc Mai My",
    "ngaySinh": "23/11/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.4,
    "diemThiFormatted": "8.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 111,
    "mshv": "YK2026-0111",
    "hoTen": "Lý Quang Quỳnh Thư",
    "ngaySinh": "07/04/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6,
    "diemThiFormatted": "6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 112,
    "mshv": "YK2026-0112",
    "hoTen": "Tạ Phương Uyên Giang",
    "ngaySinh": "18/09/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.7,
    "diemThiFormatted": "9.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 113,
    "mshv": "YK2026-0113",
    "hoTen": "Nguyễn Minh Minh Nam",
    "ngaySinh": "02/02/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.3,
    "diemThiFormatted": "7.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 114,
    "mshv": "YK2026-0114",
    "hoTen": "Trần Hoàng Cẩm Trang",
    "ngaySinh": "13/07/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.9,
    "diemThiFormatted": "4.9",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 115,
    "mshv": "YK2026-0115",
    "hoTen": "Lê Quốc Hà Hạnh",
    "ngaySinh": "24/12/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.6,
    "diemThiFormatted": "8.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 116,
    "mshv": "YK2026-0116",
    "hoTen": "Phạm Gia Lan Nhi",
    "ngaySinh": "08/05/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.2,
    "diemThiFormatted": "6.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 117,
    "mshv": "YK2026-0117",
    "hoTen": "Huỳnh Anh Nam Vân",
    "ngaySinh": "19/10/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.9,
    "diemThiFormatted": "9.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 118,
    "mshv": "YK2026-0118",
    "hoTen": "Võ Thanh Thảo Hiếu",
    "ngaySinh": "03/03/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.5,
    "diemThiFormatted": "7.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 119,
    "mshv": "YK2026-0119",
    "hoTen": "Đặng Khánh Việt Phát",
    "ngaySinh": "14/08/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.1,
    "diemThiFormatted": "5.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 120,
    "mshv": "YK2026-0120",
    "hoTen": "Bùi Đức Anh An",
    "ngaySinh": "25/01/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.8,
    "diemThiFormatted": "8.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 121,
    "mshv": "YK2026-0121",
    "hoTen": "Đỗ Thùy Đức Khoa",
    "ngaySinh": "09/06/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.4,
    "diemThiFormatted": "6.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 122,
    "mshv": "YK2026-0122",
    "hoTen": "Phan Nhật Hải Quân",
    "ngaySinh": "20/11/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4,
    "diemThiFormatted": "4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 123,
    "mshv": "YK2026-0123",
    "hoTen": "Ngô Hải Linh Bình",
    "ngaySinh": "04/04/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.7,
    "diemThiFormatted": "7.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 124,
    "mshv": "YK2026-0124",
    "hoTen": "Dương Bảo Phúc Lâm",
    "ngaySinh": "15/09/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.3,
    "diemThiFormatted": "5.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 125,
    "mshv": "YK2026-0125",
    "hoTen": "Hoàng Mai Trang Sơn",
    "ngaySinh": "26/02/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9,
    "diemThiFormatted": "9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 126,
    "mshv": "YK2026-0126",
    "hoTen": "Vũ Ngọc Yến Châu",
    "ngaySinh": "10/07/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.6,
    "diemThiFormatted": "6.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 127,
    "mshv": "YK2026-0127",
    "hoTen": "Lý Quang Bảo Long",
    "ngaySinh": "21/12/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.2,
    "diemThiFormatted": "4.2",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 128,
    "mshv": "YK2026-0128",
    "hoTen": "Tạ Phương Gia Tâm",
    "ngaySinh": "05/05/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.9,
    "diemThiFormatted": "7.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 129,
    "mshv": "YK2026-0129",
    "hoTen": "Nguyễn Minh Khánh Dũng",
    "ngaySinh": "16/10/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.5,
    "diemThiFormatted": "5.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 130,
    "mshv": "YK2026-0130",
    "hoTen": "Trần Hoàng Mai My",
    "ngaySinh": "27/03/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.2,
    "diemThiFormatted": "9.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 131,
    "mshv": "YK2026-0131",
    "hoTen": "Lê Quốc Quỳnh Thư",
    "ngaySinh": "11/08/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.8,
    "diemThiFormatted": "6.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 132,
    "mshv": "YK2026-0132",
    "hoTen": "Phạm Gia Uyên Giang",
    "ngaySinh": "22/01/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.4,
    "diemThiFormatted": "4.4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 133,
    "mshv": "YK2026-0133",
    "hoTen": "Huỳnh Anh Minh Nam",
    "ngaySinh": "06/06/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.1,
    "diemThiFormatted": "8.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 134,
    "mshv": "YK2026-0134",
    "hoTen": "Võ Thanh Cẩm Trang",
    "ngaySinh": "17/11/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.7,
    "diemThiFormatted": "5.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 135,
    "mshv": "YK2026-0135",
    "hoTen": "Đặng Khánh Hà Hạnh",
    "ngaySinh": "01/04/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.4,
    "diemThiFormatted": "9.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 136,
    "mshv": "YK2026-0136",
    "hoTen": "Bùi Đức Lan Nhi",
    "ngaySinh": "12/09/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7,
    "diemThiFormatted": "7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 137,
    "mshv": "YK2026-0137",
    "hoTen": "Đỗ Thùy Nam Vân",
    "ngaySinh": "23/02/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.6,
    "diemThiFormatted": "4.6",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 138,
    "mshv": "YK2026-0138",
    "hoTen": "Phan Nhật Thảo Hiếu",
    "ngaySinh": "07/07/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.3,
    "diemThiFormatted": "8.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 139,
    "mshv": "YK2026-0139",
    "hoTen": "Ngô Hải Việt Phát",
    "ngaySinh": "18/12/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.9,
    "diemThiFormatted": "5.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 140,
    "mshv": "YK2026-0140",
    "hoTen": "Dương Bảo Anh An",
    "ngaySinh": "02/05/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.6,
    "diemThiFormatted": "9.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 141,
    "mshv": "YK2026-0141",
    "hoTen": "Hoàng Mai Đức Khoa",
    "ngaySinh": "13/10/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.2,
    "diemThiFormatted": "7.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 142,
    "mshv": "YK2026-0142",
    "hoTen": "Vũ Ngọc Hải Quân",
    "ngaySinh": "24/03/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.8,
    "diemThiFormatted": "4.8",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 143,
    "mshv": "YK2026-0143",
    "hoTen": "Lý Quang Linh Bình",
    "ngaySinh": "08/08/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.5,
    "diemThiFormatted": "8.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 144,
    "mshv": "YK2026-0144",
    "hoTen": "Tạ Phương Phúc Lâm",
    "ngaySinh": "19/01/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.1,
    "diemThiFormatted": "6.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 145,
    "mshv": "YK2026-0145",
    "hoTen": "Nguyễn Minh Trang Sơn",
    "ngaySinh": "03/06/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.8,
    "diemThiFormatted": "9.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 146,
    "mshv": "YK2026-0146",
    "hoTen": "Trần Hoàng Yến Châu",
    "ngaySinh": "14/11/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.4,
    "diemThiFormatted": "7.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 147,
    "mshv": "YK2026-0147",
    "hoTen": "Lê Quốc Bảo Long",
    "ngaySinh": "25/04/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5,
    "diemThiFormatted": "5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 148,
    "mshv": "YK2026-0148",
    "hoTen": "Phạm Gia Gia Tâm",
    "ngaySinh": "09/09/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.7,
    "diemThiFormatted": "8.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 149,
    "mshv": "YK2026-0149",
    "hoTen": "Huỳnh Anh Khánh Dũng",
    "ngaySinh": "20/02/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.3,
    "diemThiFormatted": "6.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 150,
    "mshv": "YK2026-0150",
    "hoTen": "Võ Thanh Mai My",
    "ngaySinh": "04/07/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 10,
    "diemThiFormatted": "10",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 151,
    "mshv": "YK2026-0151",
    "hoTen": "Đặng Khánh Quỳnh Thư",
    "ngaySinh": "15/12/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.6,
    "diemThiFormatted": "7.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 152,
    "mshv": "YK2026-0152",
    "hoTen": "Bùi Đức Uyên Giang",
    "ngaySinh": "26/05/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.2,
    "diemThiFormatted": "5.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 153,
    "mshv": "YK2026-0153",
    "hoTen": "Đỗ Thùy Minh Nam",
    "ngaySinh": "10/10/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.9,
    "diemThiFormatted": "8.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 154,
    "mshv": "YK2026-0154",
    "hoTen": "Phan Nhật Cẩm Trang",
    "ngaySinh": "21/03/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.5,
    "diemThiFormatted": "6.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 155,
    "mshv": "YK2026-0155",
    "hoTen": "Ngô Hải Hà Hạnh",
    "ngaySinh": "05/08/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.1,
    "diemThiFormatted": "4.1",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 156,
    "mshv": "YK2026-0156",
    "hoTen": "Dương Bảo Lan Nhi",
    "ngaySinh": "16/01/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.8,
    "diemThiFormatted": "7.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 157,
    "mshv": "YK2026-0157",
    "hoTen": "Hoàng Mai Nam Vân",
    "ngaySinh": "27/06/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.4,
    "diemThiFormatted": "5.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 158,
    "mshv": "YK2026-0158",
    "hoTen": "Vũ Ngọc Thảo Hiếu",
    "ngaySinh": "11/11/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.1,
    "diemThiFormatted": "9.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 159,
    "mshv": "YK2026-0159",
    "hoTen": "Lý Quang Việt Phát",
    "ngaySinh": "22/04/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.7,
    "diemThiFormatted": "6.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 160,
    "mshv": "YK2026-0160",
    "hoTen": "Tạ Phương Anh An",
    "ngaySinh": "06/09/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.3,
    "diemThiFormatted": "4.3",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 161,
    "mshv": "YK2026-0161",
    "hoTen": "Nguyễn Minh Đức Khoa",
    "ngaySinh": "17/02/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8,
    "diemThiFormatted": "8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 162,
    "mshv": "YK2026-0162",
    "hoTen": "Trần Hoàng Hải Quân",
    "ngaySinh": "01/07/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.6,
    "diemThiFormatted": "5.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 163,
    "mshv": "YK2026-0163",
    "hoTen": "Lê Quốc Linh Bình",
    "ngaySinh": "12/12/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.3,
    "diemThiFormatted": "9.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 164,
    "mshv": "YK2026-0164",
    "hoTen": "Phạm Gia Phúc Lâm",
    "ngaySinh": "23/05/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.9,
    "diemThiFormatted": "6.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 165,
    "mshv": "YK2026-0165",
    "hoTen": "Huỳnh Anh Trang Sơn",
    "ngaySinh": "07/10/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.5,
    "diemThiFormatted": "4.5",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 166,
    "mshv": "YK2026-0166",
    "hoTen": "Võ Thanh Yến Châu",
    "ngaySinh": "18/03/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.2,
    "diemThiFormatted": "8.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 167,
    "mshv": "YK2026-0167",
    "hoTen": "Đặng Khánh Bảo Long",
    "ngaySinh": "02/08/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.8,
    "diemThiFormatted": "5.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 168,
    "mshv": "YK2026-0168",
    "hoTen": "Bùi Đức Gia Tâm",
    "ngaySinh": "13/01/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.5,
    "diemThiFormatted": "9.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 169,
    "mshv": "YK2026-0169",
    "hoTen": "Đỗ Thùy Khánh Dũng",
    "ngaySinh": "24/06/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.1,
    "diemThiFormatted": "7.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 170,
    "mshv": "YK2026-0170",
    "hoTen": "Phan Nhật Mai My",
    "ngaySinh": "08/11/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.7,
    "diemThiFormatted": "4.7",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 171,
    "mshv": "YK2026-0171",
    "hoTen": "Ngô Hải Quỳnh Thư",
    "ngaySinh": "19/04/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.4,
    "diemThiFormatted": "8.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 172,
    "mshv": "YK2026-0172",
    "hoTen": "Dương Bảo Uyên Giang",
    "ngaySinh": "03/09/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6,
    "diemThiFormatted": "6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 173,
    "mshv": "YK2026-0173",
    "hoTen": "Hoàng Mai Minh Nam",
    "ngaySinh": "14/02/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.7,
    "diemThiFormatted": "9.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 174,
    "mshv": "YK2026-0174",
    "hoTen": "Vũ Ngọc Cẩm Trang",
    "ngaySinh": "25/07/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.3,
    "diemThiFormatted": "7.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 175,
    "mshv": "YK2026-0175",
    "hoTen": "Lý Quang Hà Hạnh",
    "ngaySinh": "09/12/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.9,
    "diemThiFormatted": "4.9",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 176,
    "mshv": "YK2026-0176",
    "hoTen": "Tạ Phương Lan Nhi",
    "ngaySinh": "20/05/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.6,
    "diemThiFormatted": "8.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 177,
    "mshv": "YK2026-0177",
    "hoTen": "Nguyễn Minh Nam Vân",
    "ngaySinh": "04/10/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.2,
    "diemThiFormatted": "6.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 178,
    "mshv": "YK2026-0178",
    "hoTen": "Trần Hoàng Thảo Hiếu",
    "ngaySinh": "15/03/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.9,
    "diemThiFormatted": "9.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 179,
    "mshv": "YK2026-0179",
    "hoTen": "Lê Quốc Việt Phát",
    "ngaySinh": "26/08/2001",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.5,
    "diemThiFormatted": "7.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 180,
    "mshv": "YK2026-0180",
    "hoTen": "Phạm Gia Anh An",
    "ngaySinh": "10/01/1986",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.1,
    "diemThiFormatted": "5.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 181,
    "mshv": "YK2026-0181",
    "hoTen": "Huỳnh Anh Đức Khoa",
    "ngaySinh": "21/06/1993",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.8,
    "diemThiFormatted": "8.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 182,
    "mshv": "YK2026-0182",
    "hoTen": "Võ Thanh Hải Quân",
    "ngaySinh": "05/11/2000",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.4,
    "diemThiFormatted": "6.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 183,
    "mshv": "YK2026-0183",
    "hoTen": "Đặng Khánh Linh Bình",
    "ngaySinh": "16/04/1985",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4,
    "diemThiFormatted": "4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 184,
    "mshv": "YK2026-0184",
    "hoTen": "Bùi Đức Phúc Lâm",
    "ngaySinh": "27/09/1992",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.7,
    "diemThiFormatted": "7.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 185,
    "mshv": "YK2026-0185",
    "hoTen": "Đỗ Thùy Trang Sơn",
    "ngaySinh": "11/02/1999",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.3,
    "diemThiFormatted": "5.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 186,
    "mshv": "YK2026-0186",
    "hoTen": "Phan Nhật Yến Châu",
    "ngaySinh": "22/07/1984",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9,
    "diemThiFormatted": "9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 187,
    "mshv": "YK2026-0187",
    "hoTen": "Ngô Hải Bảo Long",
    "ngaySinh": "06/12/1991",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.6,
    "diemThiFormatted": "6.6",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 188,
    "mshv": "YK2026-0188",
    "hoTen": "Dương Bảo Gia Tâm",
    "ngaySinh": "17/05/1998",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.2,
    "diemThiFormatted": "4.2",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 189,
    "mshv": "YK2026-0189",
    "hoTen": "Hoàng Mai Khánh Dũng",
    "ngaySinh": "01/10/1983",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7.9,
    "diemThiFormatted": "7.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 190,
    "mshv": "YK2026-0190",
    "hoTen": "Vũ Ngọc Mai My",
    "ngaySinh": "12/03/1990",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.5,
    "diemThiFormatted": "5.5",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 191,
    "mshv": "YK2026-0191",
    "hoTen": "Lý Quang Quỳnh Thư",
    "ngaySinh": "23/08/1997",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.2,
    "diemThiFormatted": "9.2",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 192,
    "mshv": "YK2026-0192",
    "hoTen": "Tạ Phương Uyên Giang",
    "ngaySinh": "07/01/1982",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 6.8,
    "diemThiFormatted": "6.8",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 193,
    "mshv": "YK2026-0193",
    "hoTen": "Nguyễn Minh Minh Nam",
    "ngaySinh": "18/06/1989",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.4,
    "diemThiFormatted": "4.4",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 194,
    "mshv": "YK2026-0194",
    "hoTen": "Trần Hoàng Cẩm Trang",
    "ngaySinh": "02/11/1996",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.1,
    "diemThiFormatted": "8.1",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 195,
    "mshv": "YK2026-0195",
    "hoTen": "Lê Quốc Hà Hạnh",
    "ngaySinh": "13/04/1981",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.7,
    "diemThiFormatted": "5.7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 196,
    "mshv": "YK2026-0196",
    "hoTen": "Phạm Gia Lan Nhi",
    "ngaySinh": "24/09/1988",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 9.4,
    "diemThiFormatted": "9.4",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 197,
    "mshv": "YK2026-0197",
    "hoTen": "Huỳnh Anh Nam Vân",
    "ngaySinh": "08/02/1995",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 7,
    "diemThiFormatted": "7",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 198,
    "mshv": "YK2026-0198",
    "hoTen": "Võ Thanh Thảo Hiếu",
    "ngaySinh": "19/07/1980",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 4.6,
    "diemThiFormatted": "4.6",
    "ketQua": "Rớt",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 199,
    "mshv": "YK2026-0199",
    "hoTen": "Đặng Khánh Việt Phát",
    "ngaySinh": "03/12/1987",
    "gioiTinh": "Nam",
    "chuyenNganh": "Y khoa",
    "diemThi": 8.3,
    "diemThiFormatted": "8.3",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  },
  {
    "stt": 200,
    "mshv": "YK2026-0200",
    "hoTen": "Bùi Đức Anh An",
    "ngaySinh": "14/05/1994",
    "gioiTinh": "Nữ",
    "chuyenNganh": "Y khoa",
    "diemThi": 5.9,
    "diemThiFormatted": "5.9",
    "ketQua": "Đậu",
    "ghiChu": "Dữ liệu mô phỏng"
  }
];
